admin:
  audit: true # enable or disable user post need to audit.
  register: true # enable or disable register
  upload-img: 1024 # the max size of image that user can upload.
  mail: # website admin mail account to receive website notify.
  backend_url: http://127.0.0.1:8008 # manage url
  category_img: # post category image save path.
  oauth: true # enable or disable third party login like github google etc.
  ip-recognize: # recognized user login and comment ip address belong where.
    token: xxx # type your token of apispace
    url: http://ip-api.com/json
  third-party:
    github:
      enable: true
      name: Github
      icon: /static/img/github.svg
    gitee:
      enable: true
      name: Gitee
      icon: /static/img/gitee.svg
    oschina:
      enable: false
      name: OSChina
      icon: /static/img/oschina.svg
    stackoverflow:
      enable: false
      name: StackOverflow
      icon: /static/img/stackoverflow.svg
website:
  domain: http://127.0.0.1:5000 # website domain
  name: University-BBS # website name